version: "2"
run:
  timeout: 3m
linters:
  default: none
  enable:
    - bodyclose
    - contextcheck
    - errcheck
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - noctx
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
formatters:
  enable:
    - gofumpt
